# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\better_gui\better_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AcousticLevitationWindow(object):
    def setupUi(self, AcousticLevitationWindow):
        AcousticLevitationWindow.setObjectName("AcousticLevitationWindow")
        AcousticLevitationWindow.resize(1234, 898)
        AcousticLevitationWindow.setAutoFillBackground(False)
        AcousticLevitationWindow.setStyleSheet("background-color: qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147))")
        self.centralwidget = QtWidgets.QWidget(AcousticLevitationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.master_gui_title = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.master_gui_title.sizePolicy().hasHeightForWidth())
        self.master_gui_title.setSizePolicy(sizePolicy)
        self.master_gui_title.setMaximumSize(QtCore.QSize(400, 127))
        self.master_gui_title.setStyleSheet("")
        self.master_gui_title.setText("")
        self.master_gui_title.setPixmap(QtGui.QPixmap("/Users/kevinlinxc/src/ultrasonic-holography/better_gui/acoustic-levitation.png"))
        self.master_gui_title.setScaledContents(True)
        self.master_gui_title.setAlignment(QtCore.Qt.AlignCenter)
        self.master_gui_title.setObjectName("master_gui_title")
        self.verticalLayout.addWidget(self.master_gui_title)
        self.madein1week = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.madein1week.setFont(font)
        self.madein1week.setStyleSheet("color: white;")
        self.madein1week.setAlignment(QtCore.Qt.AlignCenter)
        self.madein1week.setObjectName("madein1week")
        self.verticalLayout.addWidget(self.madein1week)
        self.mode_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        self.mode_label.setFont(font)
        self.mode_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mode_label.setStyleSheet("\n"
"color: white;")
        self.mode_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mode_label.setObjectName("mode_label")
        self.verticalLayout.addWidget(self.mode_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.line_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_button.sizePolicy().hasHeightForWidth())
        self.line_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(25)
        self.line_button.setFont(font)
        self.line_button.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgb(239, 71, 111),     stop:1 rgb(239, 130, 171));\n"
"    border-radius: 20px;\n"
"    border-image: none;\n"
"    border: none;\n"
"    color: black;\n"
"    padding: 5px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #C9D6EA;\n"
"}")
        self.line_button.setObjectName("line_button")
        self.verticalLayout.addWidget(self.line_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.circle_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.circle_button.sizePolicy().hasHeightForWidth())
        self.circle_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.circle_button.setFont(font)
        self.circle_button.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgb(255, 132, 30),     stop:1 rgb(255, 182, 22));\n"
"    border-radius: 20px;\n"
"    border-image: none;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #C9D6EA;\n"
"}")
        self.circle_button.setObjectName("circle_button")
        self.verticalLayout.addWidget(self.circle_button)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.random_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.random_button.sizePolicy().hasHeightForWidth())
        self.random_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(25)
        self.random_button.setFont(font)
        self.random_button.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgb(255, 209, 102),     stop:1 rgb(255, 255, 152));\n"
"    border-radius: 20px;\n"
"    border-image: none;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #C9D6EA;\n"
"}")
        self.random_button.setObjectName("random_button")
        self.verticalLayout.addWidget(self.random_button)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        self.mouse_button = QtWidgets.QPushButton(self.centralwidget)
        self.mouse_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mouse_button.sizePolicy().hasHeightForWidth())
        self.mouse_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(25)
        self.mouse_button.setFont(font)
        self.mouse_button.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgb(63, 188, 151),     stop:1 rgb(63, 238, 201));\n"
"    border-radius: 20px;\n"
"    border-image: none;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #C9D6EA;\n"
"}")
        self.mouse_button.setObjectName("mouse_button")
        self.verticalLayout.addWidget(self.mouse_button)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.megalovania_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.megalovania_button.sizePolicy().hasHeightForWidth())
        self.megalovania_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(25)
        self.megalovania_button.setFont(font)
        self.megalovania_button.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgb(29, 139, 178),     stop:1 rgb(29, 189, 228));\n"
"    border-radius: 20px;\n"
"    border-image: none;\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #C9D6EA;\n"
"}")
        self.megalovania_button.setObjectName("megalovania_button")
        self.verticalLayout.addWidget(self.megalovania_button)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem5)
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_button.sizePolicy().hasHeightForWidth())
        self.stop_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(25)
        self.stop_button.setFont(font)
        self.stop_button.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgb(149, 81, 166),     stop:1 rgb(149, 131, 216));\n"
"    border-radius: 20px;\n"
"    border-image: none;\n"
"    border: none;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid #C9D6EA;\n"
"}")
        self.stop_button.setObjectName("stop_button")
        self.verticalLayout.addWidget(self.stop_button)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem6)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.big_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.big_label.sizePolicy().hasHeightForWidth())
        self.big_label.setSizePolicy(sizePolicy)
        self.big_label.setMaximumSize(QtCore.QSize(1300, 1300))
        self.big_label.setAlignment(QtCore.Qt.AlignCenter)
        self.big_label.setObjectName("big_label")
        self.horizontalLayout.addWidget(self.big_label)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 20)
        AcousticLevitationWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AcousticLevitationWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1234, 22))
        self.menubar.setObjectName("menubar")
        AcousticLevitationWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AcousticLevitationWindow)
        self.statusbar.setObjectName("statusbar")
        AcousticLevitationWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AcousticLevitationWindow)
        QtCore.QMetaObject.connectSlotsByName(AcousticLevitationWindow)

    def retranslateUi(self, AcousticLevitationWindow):
        _translate = QtCore.QCoreApplication.translate
        AcousticLevitationWindow.setWindowTitle(_translate("AcousticLevitationWindow", "MainWindow"))
        self.madein1week.setText(_translate("AcousticLevitationWindow", "(made in 1 week)"))
        self.mode_label.setText(_translate("AcousticLevitationWindow", "Mode: Stopped"))
        self.line_button.setText(_translate("AcousticLevitationWindow", "Line Path"))
        self.circle_button.setText(_translate("AcousticLevitationWindow", "Circle Path"))
        self.random_button.setText(_translate("AcousticLevitationWindow", "Random Path"))
        self.mouse_button.setText(_translate("AcousticLevitationWindow", "Mouse Control"))
        self.megalovania_button.setText(_translate("AcousticLevitationWindow", "Megalovania"))
        self.stop_button.setText(_translate("AcousticLevitationWindow", "STOP"))
        self.big_label.setText(_translate("AcousticLevitationWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AcousticLevitationWindow = QtWidgets.QMainWindow()
    ui = Ui_AcousticLevitationWindow()
    ui.setupUi(AcousticLevitationWindow)
    AcousticLevitationWindow.show()
    sys.exit(app.exec_())
